name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


  http: ^0.13.3
  shared_preferences: ^0.5.6+1
  url_launcher: ^5.4.1
  flutter_html: ^0.10.2
  awesome_dialog: ^1.3.1
#  cached_network_image:
  provider: ^4.0.4
  animated_text_kit: ^2.0.0
  chewie:
  video_player:
  path_provider:
  percent_indicator: ^2.1.1+1
  animated_icon_button: ^1.0.2
  encrypt:
  sqflite: ^1.2.0
  webview_flutter:
  aes_crypt:
  flutter_zip_archive:
    path: flutter_zip_archive
  progress_dialog:
  flutter_webview_plugin: ^0.3.11
  najvaflutter: ^1.3.0
#  camera: ^0.5.8+2
  file_picker: ^1.4.3+2
  image:
  photofilters:
  syncfusion_flutter_datepicker:
  platform_device_id:
  uni_links: ^0.4.0
  flutter_windowmanager:
  flowder: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/user.png
    - assets/website.png
    - assets/instagram.png
    - assets/telegram.png
    - assets/home.png
    - assets/back.png
    - assets/info.png
    - assets/video.png
    - assets/profile.png
    - assets/asatir.png
    - assets/avatar.png
    - images/
    - images/whatsapp.png
    - assets/testfile.txt.enc

     # An image asset can refer to one or more resolution-specific "variants", see
     # https://flutter.dev/assets-and-images/#resolution-aware.

     # For details regarding adding assets from package dependencies, see
     # https://flutter.dev/assets-and-images/#from-packages

     # To add custom fonts to your application, add a fonts section here,
     # in this "flutter" section. Each entry in this list should have a
     # "family" key with the font family name, and a "fonts" key with a
     # list giving the asset and other descriptors for the font. For
     # example:
  fonts:
   - family: meysam
     fonts:
        #      - asset: fonts/IranNastaliq.ttf
       - asset: fonts/iransans.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#   - family: font1
#     fonts:
#       - asset: fonts/ballz.ttf
#   - family: font2
#     fonts:
#       - asset: fonts/heaters.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
